name: Release Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  checkversions:
    runs-on: ubuntu-latest

    outputs:
      ver: ${{ steps.set.outputs.ver }}
      rel: ${{ steps.set.outputs.rel }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set versions
        id: set
        run: |
          echo "ver=$(cat VERSION)" >> $GITHUB_OUTPUT
          echo "rel=$(cat RELEASE_VERSION)" >> $GITHUB_OUTPUT

      - name: Display versions
        run: |
          echo ">>>>> ver is ${{ steps.set.outputs.ver }}"
          echo ">>>>> rel is ${{ steps.set.outputs.rel }}"

  build-and-push:
    needs: checkversions
    runs-on: ubuntu-latest
    if: ${{ needs.checkversions.outputs.ver == needs.checkversions.outputs.rel }}

    steps:
      - name: Display versions
        run: |
          echo ">>>>> ver is ${{ needs.checkversions.outputs.ver }}"
          echo ">>>>> rel is ${{ needs.checkversions.outputs.rel }}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build jar
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t healthylifestyle/backend:${{ needs.checkversions.outputs.ver }} -t healthylifestyle/backend:latest .
        
      - name: Push image to Docker Hub
        run: |
          docker push healthylifestyle/backend:${{ needs.checkversions.outputs.ver }}
          docker push healthylifestyle/backend:latest
